# Data
path: /content/drive/MyDrive/Computer_Vision_&_Deep_Learning/DATASET/Training_Test_Datasets/Training_Test_Val
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')
test: images/test

# Keypoints
kpt_shape: [7, 3]  # [number of keypoints, number of dim]


# Classes
names:
  0: staffa
